/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rz.guiform;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.InetAddress;
import java.net.NetworkInterface;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;

/**
 *
 * @author developer
 */
public class SferyxBeanFrame extends JFrame {

    /**
     * Creates new form TestBeanFrame
     */
    public SferyxBeanFrame() {
        initComponents();
        //getMacAddress(); --OK
        macTest();
    }

    public static void getMacAddress() {
        InetAddress ip;
        try {
            ip = InetAddress.getLocalHost();
            ip = InetAddress.getByName("192.168.0.148");
            ip = InetAddress.getByName("Developer");
            System.out.println("Current IP address : " + ip.getHostAddress());
            NetworkInterface network = NetworkInterface.getByInetAddress(ip);
            byte[] mac = network.getHardwareAddress();
            System.out.print("Current MAC address : ");
            StringBuilder sb = new StringBuilder();
            for (int i = 0; i < mac.length; i++) {
                sb.append(String.format("%02X%s", mac[i], (i < mac.length - 1) ? "-" : ""));
            }
            System.out.println(sb.toString());
        } catch (UnknownHostException e) {
            e.printStackTrace();
        } catch (SocketException e) {
            e.printStackTrace();//12-40-F3-EE-A9-64
            //10:40:f3:ee:7b:1e
        }

        /*Process p;
        try {
            p = Runtime.getRuntime().exec("getmac /fo csv /nh");
            java.io.BufferedReader in = new java.io.BufferedReader(new java.io.InputStreamReader(p.getInputStream()));
            String line;
            line = in.readLine();
            String[] result = line.split(",");

            System.out.println(result[0].replace('"', ' ').trim());
        } catch (IOException ex) {
            Logger.getLogger(SferyxBeanFrame.class.getName()).log(Level.SEVERE, null, ex);
        }*/
        final NetworkInterface netInf;
        try {
            netInf = NetworkInterface.getNetworkInterfaces().nextElement();
            final byte[] mac = netInf.getHardwareAddress();
            final StringBuilder sb = new StringBuilder();
            for (int i = 0; i < mac.length; i++) {
                sb.append(String.format("%02X%s", mac[i], (i < mac.length - 1) ? "-" : ""));
            }
            System.out.println("Mac addr: {} " + sb.toString());
        } catch (SocketException ex) {
            Logger.getLogger(SferyxBeanFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public static void macTest() {
        System.out.println("MAC_TEST_RUN");
        String command = "ipconfig /all";
        Process p;
        try {
            //p = Runtime.getRuntime().exec(command);
            p = Runtime.getRuntime().exec("ifconfig");
            BufferedReader inn = new BufferedReader(new InputStreamReader(p.getInputStream()));
            Pattern pattern = Pattern.compile(".*Physical Addres.*: (.*)");

            while (true) {
                String line = inn.readLine();

                if (line == null) {
                    break;
                }
                //System.out.println("MAC_TEST" + line);
                Matcher mm = pattern.matcher(line);
                if (mm.matches()) {
                    System.out.println("MAC_TEST" + mm.group(1));
                }
            }
            /*String line=null;
            while ((line = inn.readLine()) != null) {
                System.out.println("MAC_TEST" + line);
            }*/
        } catch (IOException ex) {
            Logger.getLogger(SferyxBeanFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        hTMLEditor1 = new sferyx.administration.editors.HTMLEditor();
        jPanel1 = new javax.swing.JPanel();
        getContentButton = new javax.swing.JButton();
        insertTableButton = new javax.swing.JButton();
        insertCheckBoxbutton = new javax.swing.JButton();
        insertOrderedListButton = new javax.swing.JButton();
        insertUnorderedList = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        hTMLEditor1.setContent("");
        hTMLEditor1.setRemovedMenuItems("menuFile, menuEdit");
        hTMLEditor1.setRemovedMenus("printFileMenuItem,openFileMenuItem ,newFileMenuItem ");
        hTMLEditor1.setRemovedToolbarItems("openFileButton, printFileButton");
        hTMLEditor1.setStatusMessage("Hello");
        hTMLEditor1.setTableItemsStatus(true);
        getContentPane().add(hTMLEditor1, java.awt.BorderLayout.CENTER);

        getContentButton.setText("getContent");
        getContentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getContentButtonActionPerformed(evt);
            }
        });

        jPanel1.add(getContentButton);

        insertTableButton.setText("insertTable");
        insertTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertTableButtonActionPerformed(evt);
            }
        });

        jPanel1.add(insertTableButton);

        insertCheckBoxbutton.setText("insertCheckbox");
        insertCheckBoxbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertCheckBoxbuttonActionPerformed(evt);
            }
        });

        jPanel1.add(insertCheckBoxbutton);

        insertOrderedListButton.setText("OrderedList");
        insertOrderedListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertOrderedListButtonActionPerformed(evt);
            }
        });

        jPanel1.add(insertOrderedListButton);

        insertUnorderedList.setText("UnorderedList");
        insertUnorderedList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertUnorderedListActionPerformed(evt);
            }
        });

        jPanel1.add(insertUnorderedList);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        pack();
    }//GEN-END:initComponents

    private void insertUnorderedListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertUnorderedListActionPerformed
        // Add your handling code here:
        //hTMLEditor1.insertUnorderedList();
    }//GEN-LAST:event_insertUnorderedListActionPerformed

    private void insertOrderedListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertOrderedListButtonActionPerformed
        // Add your handling code here:
        //hTMLEditor1.insertOrderedList();
    }//GEN-LAST:event_insertOrderedListButtonActionPerformed

    private void insertCheckBoxbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertCheckBoxbuttonActionPerformed
        // Add your handling code here:
        //hTMLEditor1.insertCheckBox();
    }//GEN-LAST:event_insertCheckBoxbuttonActionPerformed

    private void insertTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertTableButtonActionPerformed
        // Add your handling code here:
        //hTMLEditor1.insertTable(10,10);
    }//GEN-LAST:event_insertTableButtonActionPerformed

    private void getContentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getContentButtonActionPerformed
        // Add your handling code here:
        System.out.println(hTMLEditor1.getContent());
    }//GEN-LAST:event_getContentButtonActionPerformed

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new SferyxBeanFrame().show();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton getContentButton;
    private sferyx.administration.editors.HTMLEditor hTMLEditor1;
    private javax.swing.JButton insertOrderedListButton;
    private javax.swing.JButton insertTableButton;
    private javax.swing.JButton insertCheckBoxbutton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton insertUnorderedList;
    // End of variables declaration//GEN-END:variables
}
//https://www.sferyx.com/htmleditor/
